### ISSUE TITLE
Execute Bash in Text Field

### ISSUE THREAD

**Issue by destinyb-realityi** [8398a7/action-slack#106]
**Is your feature request related to a problem? Please describe.**
I'm trying to execute a bash command in the `with -> text` field to get the URL where files were uploaded to.

**Describe the solution you'd like**
When an action is successful, I'd like to be able to send in Slack the exact URL where to download the built files. Right now I'm trying to execute bash to get the URL, however, it's not executing. 

**Describe alternatives you've considered**
I tried setting the URL as an environmental variable but I had no luck.

**Additional context**

**Comment by 8398a7** [comment]
> I'd like to be able to send in Slack the exact URL where to download the built files. 

Is this an artifact?
I don't plan to allow bash to run, but it might be possible to include the artifact download url in the notification.

**Comment by 8398a7** [comment]
I have experimented with this, but unfortunately there is no way to get the artifact id.
Since the artifact id is determined after the entire workflow is completed, there is no way to know the artifact id when you are notified within the same workflow.

**Comment by 8398a7** [comment]
@destinyb-realityi No response, so I'll close it.
Re-open if there is additional information.
