### ISSUE TITLE
Validate SLACK_WEBHOOK_URL

### ISSUE THREAD

**Issue by sorawee** [8398a7/action-slack#118]
**Is your feature request related to a problem? Please describe.**

Say, a user made a typo like:

```
SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK.URL }}
```

the value of `SLACK_WEBHOOK_URL` would be `null`. This results in an obscure error like:

```
Cannot read property 'replace' of null
```

**Describe the solution you'd like**

Validate that `SLACK_WEBHOOK_URL` must be a string.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by 8398a7** [comment]
Thanks for the report.
I fixed it in v3.8.1.
