### ISSUE TITLE
Is it possible to trigger notification only on failure ?

### ISSUE THREAD

**Issue by smknstd** [8398a7/action-slack#12]

**Comment by 8398a7** [comment]
Have you read the official documentation?

**Comment by smknstd** [comment]
Yes I did and I couldn't figure it out. To me the first line of the parameters table is pretty confusing

![status-slack](https://user-images.githubusercontent.com/2412608/67262956-db269c80-f4a6-11e9-8414-7b2fdd2481a7.png)

What behavior should I expect with  `status: failure` ?

**Comment by 8398a7** [comment]
No, the official I am saying is the Github Actions documentation.

> Is it possible to trigger notification only on failure ?

This is a story about how to fire an event when GitHub Actions fails, not related to the library.
The library's README is not a wrapper around the official documentation, so you should check it out.

**Comment by smknstd** [comment]
Thanks for your answer ! I got it. 

> This is a story about how to fire an event when GitHub Actions fails, not related to the library.

Might be useful to mention this in the doc as some feature depends on job status (mention only when fails ...), it was a bit confusing to me.

So I got it working like this, good job on this package !
```
    - uses: 8398a7/action-slack@v2.4.0
      if: failure()
      with:
        status: failure
```
