### ISSUE TITLE
icon_url legacy property not working 

### ISSUE THREAD

**Issue by eriknyk** [8398a7/action-slack#132]
**Describe the bug**
icon_url legacy property not working 

**To Reproduce**
I set the property but it is not being applied

**Expected behavior**
slack display the custom icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/205721/111412262-19c78300-86aa-11eb-9346-2e909d28d0bb.png)

```
SLACK_WEBHOOK_URL = https://hooks.slack.com/services/.../...
```

**Comment by 8398a7** [comment]
It only works with the old incoming webhook url, is the one you are using the old one?

**Comment by eriknyk** [comment]
Sorry, I have no idea how to know if the webhook I’m using is the old one or newest.

**Comment by 8398a7** [comment]
I think it's a good idea to refer to the slack documentation.

**Comment by RaJiska** [comment]
> It only works with the old incoming webhook url, is the one you are using the old one?

Any chances of having it to work with the new one in the future ?

**Comment by 8398a7** [comment]
@RaJiska This is a specification of slack.
If the specification of slack changes, it may be supported.
