### ISSUE TITLE
Total execution time is undefined

### ISSUE THREAD

**Issue by lukaslau** [8398a7/action-slack#146]
**Describe the bug**
${process.env.AS_TOOK} returns always 'undefined' value

**To Reproduce**
Workflow file I use: https://pastebin.com/XcR8RMjn
Self-hosted github runner was used

**Expected behavior**
I want to get total time of execution

**Screenshots**
https://i.imgur.com/7PW7h9r.png

**Comment by 8398a7** [comment]
If `name` is changed when using matrix, it will not work.
This specification will be described in the documentation.

I have also created an issue for it to work.
If there is further discussion, please do so here.
refs: #150
