### ISSUE TITLE
'Job is not found' links are broken

### ISSUE THREAD

**Issue by astone123** [8398a7/action-slack#233]
Both of the links in this error message are broken.

https://action-slack.netlify.app/with#job_name
and
https://action-slack.netlify.app/fields

https://github.com/8398a7/action-slack/blob/b88557f91bdbe37434043070c34568d9314b4223/__tests__/incorrectMatrix.test.ts#L61

These links should be updated to point to pages in the documentation

**Comment by hwood-fg** [comment]
Fixed in #242
