### ISSUE TITLE
Enable Security Advisories / Security Contact

### ISSUE THREAD

**Issue by R3x** [8398a7/action-slack#235]
Hello,

I would like to report a security vulnerability in private, I was not able to find a security contact for this repository and there is no security policy and private reporting is disabled as well. What would be a good contact to reach out to? Or would you be open to enabling private vulnerability reporting for the repository?

**Comment by 8398a7** [comment]
Hello. Thank you for contacting me.
I have enabled "Private vulnerability reporting".
Could you please report back from there?

**Comment by R3x** [comment]
Thanks!
