### ISSUE TITLE
Get duration

### ISSUE THREAD

**Issue by elalemanyo** [8398a7/action-slack#38]
Hi,
Would be great if I can show the duration time, is it possible?

Thanks!

**Comment by 8398a7** [comment]
Thanks for your comment. I will look into the duration can get.

**Comment by 8398a7** [comment]
It seems to be able to get.

https://developer.github.com/v3/actions/workflows/
https://developer.github.com/v3/actions/workflow_jobs/
https://developer.github.com/v3/actions/workflow_runs/

**Comment by 8398a7** [comment]
Getting the run_id seems a bit difficult.
It seems that it can be passed via environment variables ...

**Comment by 8398a7** [comment]
run_id cannot be obtained from the github object of javascript, but it can be obtained with environment variables, so I will consider correspondence there.

refs: https://github.community/t5/GitHub-Actions/How-to-get-the-quot-run-quot-ID/m-p/45657/highlight/true#M6301

**Comment by 8398a7** [comment]
As a result of investigation, it seems necessary to make changes that break compatibility(#43).
Since it needs to be released as v3, this feature addition seems to be still ahead.

**Comment by 8398a7** [comment]
GET `https://api.github.com/repos/8398a7/action-slack/actions/runs/:run_id/jobs`
Get the jobs list.
run_id is in the environment variable `GITHUB_RUN_ID`.

I need to compare the name in the jobs list with the payload.workflow automatically provided by GitHub Actions, and get the started_at/completed_at of the match.

<details>
<summary>logs</summary>

[build-test job](https://github.com/8398a7/action-slack/files/4240703/logs_530.zip)
[notification job](https://github.com/8398a7/action-slack/files/4240704/logs_531.zip)
</details>

**Comment by FonsRademakers** [comment]
Hi,  do you have a simple example how to show duration time?

Thanks, Fons.

**Comment by 8398a7** [comment]
This feature is not yet implemented.
