### ISSUE TITLE
Use variables inside payload

### ISSUE THREAD

**Issue by elalemanyo** [8398a7/action-slack#39]
Hi,
How can I use the variables inside value from a custom notification?

I am trying to do something like this:

```
value: "deployed version GITHUB_SHA.",
```

What I am doing wrong?

**Comment by outtoin** [comment]
+1

**Comment by elalemanyo** [comment]
Ok, this is working for me:
`value: "deployed version ${{ github.sha }}.",`

**Comment by 8398a7** [comment]
@elalemanyo 
Is it okay to close because the problem seems to be solved?
