### ISSUE TITLE
Question on when GITHUB_TOKEN is required?

### ISSUE THREAD

**Issue by unicell** [8398a7/action-slack#40]
When comparing similar Github Action on marketplace that sends notification to Slack:

- https://github.com/marketplace/actions/github-action-for-slack
- https://github.com/marketplace/actions/slack-notify
- https://github.com/marketplace/actions/send-message-to-slack

None of those requires GITHUB_TOKEN as part of the config. Wondering why it is needed, and whether it can be optional? Thanks!

**Comment by 8398a7** [comment]
Thanks for your comment.

I use it to get the commit message with API.
https://github.com/8398a7/action-slack/blob/master/src/client.ts#L99
However, there is also a method that does not require GITHUB_TOKEN and only takes it when specified.
It is my laziness that GITHUB_TOKEN is required.

**Comment by 8398a7** [comment]
Released in v2.7.0
The specification of GITHUB_TOKEN is optional.
