### ISSUE TITLE
pull request の場合の action のリンク

### ISSUE THREAD

**Issue by technote-space** [8398a7/action-slack#49]
## 概要
merge ref の sha が対象になっているため、スクリーンショットのようにアクションの結果が見れない

## 考えうる解決方法

head ref の sha を対象にする

## スクリーンショット

![merge ref](https://user-images.githubusercontent.com/39912269/76140057-e7984400-6099-11ea-8dc6-97bc8fe11efd.png)

**Comment by 8398a7** [comment]
こちらの機能はv3ブランチにマージしました。
まだ正式リリースできないためタグは打っていませんが、 `8398a7/action-slack@v3` で利用できると思います。
