### ISSUE TITLE
DeprecationWarning が発生する

### ISSUE THREAD

**Issue by technote-space** [8398a7/action-slack#52]
## 概要

以下の Warning が発生する

```
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

## 考えうる解決方法

色々調べてみましたが、原因は `@slack/webhook@5.0.2` が 使用している `axios@^0.18.0` のようです。

https://github.com/axios/axios/commit/787c808c0401b766d2769097cef864dd1cfb536b

先月修正されて 5.0.3 として公開されています。

https://github.com/slackapi/node-slack-sdk/commit/47154ebb44a978d3afc9257deb0eaf818c2a7ed0

@slack/webhook を 5.0.3 に上げて確認しましたが、 Slackが正しく送信されることと Warning が発生しないことを確認しました。

![no-warning](https://user-images.githubusercontent.com/39912269/77181579-e55ccd80-6b0e-11ea-8fc1-684b031f3a1b.png)

v3に向けて色々調整もあると思うので、様子を見てバージョンを上げてみてください。

**Comment by 8398a7** [comment]
ありがとうございます。更新しておきました
