### ISSUE TITLE
Single quote in commit message causes an error

### ISSUE THREAD

**Issue by xird** [8398a7/action-slack#68]
I got this error from a Slack integration that worked fine before:

```
##[error]Unexpected identifier
```

After a bit of digging, I realized that it was the fact that the first commit message of the branch had a single quote in it, which means the PR name also had it. It seems that action-slack doesn't escape the strings properly, and errors out.

This was on v2.

**Comment by 8398a7** [comment]
Thanks for the report.
You're right, I don't remember putting in the escape process.

I'll fix it soon.

**Comment by 8398a7** [comment]
As far as I can tell, it's working fine as far as I can tell.
[Here's](https://github.com/8398a7/action-slack/runs/769483425?check_suite_focus=true) a concrete example.

There may be other factors, but I don't know, so if you have any additional information, please let me know.

**Comment by 8398a7** [comment]
I would like you to update to v3 and see if you get the same symptoms.

**Comment by 8398a7** [comment]
Please open again if there is reproduction information.
