### ISSUE TITLE
Optional GITHUB_TOKEN

### ISSUE THREAD

**Issue by botnerd** [8398a7/action-slack#7]
I'm using the custom status to create my own slack message. Since I'm doing that it doesn't need the `GITHUB_TOKEN`. Would it be possible to make it optional for custom messages?

**Comment by 8398a7** [comment]
As you say, `GITHUB_TOKEN` isn't required for custom.
The reason why it was essential was simplification in implementation.

However, since it has been requested, we will consider making it optional.

**Comment by botnerd** [comment]
Thank you very much.

**Comment by 8398a7** [comment]
I released the optional version as v2.4.0.
It is available on v2 branch.

**Comment by botnerd** [comment]
Just tried it out and it works great! Thanks again.

**Comment by csexton** [comment]
Wow, that was fast turn around. Thanks!

**Comment by 8398a7** [comment]
refs: #40
