### ISSUE TITLE
Allow to mention user groups

### ISSUE THREAD

**Issue by nileshr** [8398a7/action-slack#73]
According to [Slack's documentation](https://api.slack.com/reference/surfaces/formatting#mentioning-groups), in order to mention user group we need to follow the following syntax `!subteam^ID`.
I think this will be very easy to support, since mentioning special groups like `here` & `channel` is already supported. If we add check for `subteam^` [here](https://github.com/8398a7/action-slack/blob/master/src/client.ts#L33), I think the rest should work fine.

I'm happy to take up this change if it seems okay.

**Comment by jfunke-well** [comment]
I wasn't able to get `mention:` to work at all.  Tried with `mention: here`

**Comment by nileshr** [comment]
@jfunke-well It worked for me with a `user_id`. Maybe you need to also include `if_mention`?

**Comment by nileshr** [comment]
@8398a7 Should I go ahead with the sub team change?

**Comment by 8398a7** [comment]
@nileshr I think it's good.

If I were to make a change, it would be around here.
https://github.com/8398a7/action-slack/blob/master/src/client.ts#L303-L304

**Comment by nileshr** [comment]
@8398a7 Sure, I'll give it a shot.

**Comment by 8398a7** [comment]
@nileshr Thanks for contributing again.
It was released as v3.3.0.
