### ISSUE TITLE
The Took field is empty

### ISSUE THREAD

**Issue by vasanthgeethanraju** [8398a7/action-slack#90]
I followed the steps from this link - [action-slack](https://github.com/marketplace/actions/action-slack) but the overall build time (duration) is not visible in `took` field. What am I missing? 

I tried adding `MATRIX_CONTEXT: ${{ toJson(matrix) }}` code but it didn't work as well. Maybe additional configurations for the matrix are not explained well. Is there a way to display it without using `MATRIX_CONTEXT`? 

<img width="706" alt="Screen Shot 2020-07-17 at 1 31 34 PM" src="https://user-images.githubusercontent.com/10342605/87826056-7893de80-c835-11ea-809f-a9f8600eb52b.png">

**Comment by 8398a7** [comment]
If this is true, the job name should be the name of the matrix.
e.g. `build (ubuntu-18.04)`

If possible, I would like to see the yaml you have set up.

refs: https://action-slack.netlify.app/fields

**Comment by vasanthgeethanraju** [comment]
I'm sorry I think I must have made some typo errors. I added `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` and it worked! 
PS: Not using `MATRIX_CONTEXT`

Thanks and closing the issue. 
<img width="615" alt="Screen Shot 2020-07-20 at 1 49 39 PM" src="https://user-images.githubusercontent.com/10342605/87979832-e3405680-ca8f-11ea-9977-b66c83e8d595.png">
