### ISSUE TITLE
MATRIX_CONTEXT will not work if more than one property is specified in the matrix

### ISSUE THREAD

**Issue by KoheiKanagu** [8398a7/action-slack#95]
**Describe the bug**

The URL of the job is undefined.
<img width="532" alt="スクリーンショット 2020-08-06 18 25 54" src="https://user-images.githubusercontent.com/6175794/89515583-4b25c980-d812-11ea-8a2d-fb2935d52537.png">

If there is only one property, then the job URL is correct.

Here are the yml and jobs that are causing the problem.
- https://github.com/KoheiKanagu/flutter_playground/blob/20200806_64bd6e2/.github/workflows/playground.yml
- https://github.com/KoheiKanagu/flutter_playground/runs/952915036?check_suite_focus=true

**Comment by 8398a7** [comment]
Thanks for the report.
As you mentioned, having multiple properties on the matrix won't work.
refs: https://github.com/KoheiKanagu/flutter_playground/blob/64bd6e25b843a3106e1f14dbf44b26d593250945/.github/workflows/playground.yml#L12

I will consider how to fix it.

**Comment by 8398a7** [comment]
For a simple solution to this problem it would be nice to be able to get the job_id information from the toolkit.
This has been reported in the issue.

https://github.com/actions/toolkit/issues/550

**Comment by 8398a7** [comment]
@KoheiKanagu 
I came up with a workaround and I responded to it.
Can you confirm that it is behaving as expected?

It is released in v3.5.1.

**Comment by KoheiKanagu** [comment]
@8398a7 
Thank you for the fix.
Job's URL has come to do a great job.
<img width="521" alt="スクリーンショット 2020-08-07 22 20 43" src="https://user-images.githubusercontent.com/6175794/89649790-49d0cb80-d8fc-11ea-8080-b57b43089983.png">
