### ISSUE TITLE
Took is not populating

### ISSUE THREAD

**Issue by owenniblock** [8398a7/action-slack#96]
**Describe the bug**
Our Slack output has the `took` column but it's blank.

We can tell the GITHUB)TOKEN is working correctly because the `message` appears filled out.

**To Reproduce**
1. Use the following yml:
>         fields: repo,workflow,took,message # default: repo,commit

**Expected behavior**
Took should be populated

**Comment by 8398a7** [comment]
Can you show me the whole setup?
If you are using `matrix`, took will not be displayed unless you set it up properly.

**Comment by owenniblock** [comment]
You are absolutely right, I had forgotten the note about `matrix` use. Closing - thanks!
